FROM node

WORKDIR /app

RUN apt-get update
RUN apt-get install ffmpeg -y

COPY package.json ./
COPY yarn.lock ./

RUN npm install yarn
RUN rm package-lock.json
RUN yarn

COPY ./ ./

EXPOSE 5000
CMD [ "yarn", "dev" ]
